# Generated by Django 4.1.2 on 2022-10-20 13:42

import datetime
from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="User",
            fields=[
                (
                    "userId",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("username", models.CharField(max_length=12, unique=True)),
                ("password", models.CharField(max_length=128)),
                ("role", models.CharField(default="USER", max_length=5)),
                ("fullname", models.CharField(max_length=32)),
                ("email", models.EmailField(max_length=50)),
                ("created_at", models.DateField(default=datetime.date.today)),
            ],
        ),
    ]
